"""One natural-language query API for every backend.

:class:`Text2Query` picks the right translator from the backend:
:class:`~cvcdocdb.text2sparql.Text2SPARQL` on a SPARQL backend
(:class:`~cvcdocdb.jena_graph.JenaGraph`) and
:class:`~cvcdocdb.text2cypher.Text2Cypher` on every other one
(``NetworkXGraph``, ``Neo4jGraph``, ``MemgraphGraph``)::

    from cvcdocdb import Text2Query

    t2q = Text2Query(graph, llm=my_llm)
    result = t2q.query("Quantes pàgines té el document D1?")
    result.language  # "sparql" or "cypher"
    result.query     # the generated query (already executed)
    result.records   # [{'c': 2}]

Errors are :class:`Text2QueryError` (the base of ``Text2CypherError`` and
``Text2SPARQLError``).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from .text2cypher import Text2Cypher, Text2QueryError
from .text2sparql import Text2SPARQL, _is_sparql_graph

__all__ = ["Text2Query", "Text2QueryError", "Text2QueryResult"]


@dataclass
class Text2QueryResult:
    """Answer to a natural-language question.

    Attributes:
        query: The query generated by the LLM (and executed).
        language: ``"cypher"`` or ``"sparql"``.
        records: Query results, shaped like ``graph.query(query)``.
        metadata: The translator's own metadata.
    """

    query: str
    language: str
    records: List[Dict[str, Any]]
    metadata: Dict[str, Any] = field(default_factory=dict)


class Text2Query:
    """Ask natural-language questions to any cvcdocdb graph.

    Args:
        graph: Any cvcdocdb backend.
        llm: The LLM handle (see :class:`~cvcdocdb.text2cypher.Text2Cypher`).
        schema: Schema text for the prompt; introspected when omitted.
        examples: Optional example question/query pairs for the prompt.
        custom_prompt: Optional prompt template with ``{schema}``,
            ``{examples}`` and ``{query_text}`` placeholders.
        database: Neo4j only — database to query; defaults to the graph's.

    Attributes:
        language: ``"sparql"`` or ``"cypher"``.
        translator: The underlying :class:`~cvcdocdb.text2sparql.Text2SPARQL`
            or :class:`~cvcdocdb.text2cypher.Text2Cypher`.
        schema: The schema text shown to the LLM.

    Raises:
        TypeError: As the translators, or if *database* is given for a
            SPARQL backend.
    """

    def __init__(
        self,
        graph: Any,
        llm: Any,
        *,
        schema: Optional[str] = None,
        examples: Optional[List[str]] = None,
        custom_prompt: Optional[str] = None,
        database: Optional[str] = None,
    ) -> None:
        if _is_sparql_graph(graph):
            if database is not None:
                raise TypeError("'database' only applies to Neo4j; JenaGraph doesn't take it")
            self.language = "sparql"
            self.translator: Any = Text2SPARQL(
                graph, llm, schema=schema, examples=examples, custom_prompt=custom_prompt
            )
        else:
            self.language = "cypher"
            self.translator = Text2Cypher(
                graph, llm, schema=schema, examples=examples, custom_prompt=custom_prompt, database=database
            )
        self.schema = self.translator.schema

    def query(self, question: str) -> Text2QueryResult:
        """Translate *question* with the LLM, run it, return the rows.

        Raises:
            Text2QueryError: If the generated query is invalid or not
                read-only (nothing is executed in that case).
        """
        result = self.translator.query(question)
        generated = result.sparql if self.language == "sparql" else result.cypher
        return Text2QueryResult(query=generated, language=self.language,
                                records=result.records, metadata=result.metadata)
