"""Natural-language questions over a SPARQL backend (:class:`~cvcdocdb.jena_graph.JenaGraph`).

:class:`Text2SPARQL` is the SPARQL counterpart of
:class:`~cvcdocdb.text2cypher.Text2Cypher`, with the same API::

    from cvcdocdb import JenaGraph, Text2SPARQL

    t2s = Text2SPARQL(graph, llm=my_llm)            # graph: a JenaGraph
    result = t2s.query("Quantes pàgines té el document D1?")
    result.sparql    # "PREFIX label: <urn:cvcdocdb:label/> SELECT ..."
    result.records   # [{'c': 2}] — same shape as graph.query(sparql)

The LLM gets the graph schema in the RDF vocabulary JenaGraph writes (with
``PREFIX`` declarations for its namespace) and the question. The query it
returns is only run if it is read-only: a ``SELECT``/``ASK``/``CONSTRUCT``/
``DESCRIBE`` with no update operation and no ``SERVICE`` (federated queries
could reach other servers). Anything else raises :class:`Text2SPARQLError`.

:class:`~cvcdocdb.text2query.Text2Query` picks Text2SPARQL or Text2Cypher
from the backend. No extra dependency is needed.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Sequence, Tuple
from urllib.parse import quote

from .text2cypher import CallableLLM, Text2QueryError, collect_schema

__all__ = [
    "DEFAULT_SPARQL_PROMPT",
    "Text2SPARQL",
    "Text2SPARQLError",
    "Text2SPARQLResult",
    "extract_sparql",
    "format_sparql_schema",
    "is_read_only_sparql",
]

DEFAULT_SPARQL_PROMPT = """Task: Generate a SPARQL 1.2 query for querying an RDF graph from a user input.

Schema:
{schema}

Examples (optional):
{examples}

Input:
{query_text}

Do not use any classes, properties or relationships not included in the schema.
Declare every PREFIX you use. Read relationship properties with the RDF 1.2
annotation syntax, e.g. ?a rel:X ?b {{| prop:p ?v |}} .
Do not include triple backticks ``` or any additional text except the generated SPARQL query in your response.

SPARQL query:
"""

_QUERY_FORMS = ("SELECT", "ASK", "CONSTRUCT", "DESCRIBE")
_FORBIDDEN = re.compile(
    r"(?<![\w:?$])(INSERT|DELETE|LOAD|CLEAR|DROP|CREATE|ADD|MOVE|COPY|SERVICE)(?![\w:])",
    re.IGNORECASE,
)
_STRINGS_AND_IRIS = re.compile(
    r'"""[\s\S]*?"""|\'\'\'[\s\S]*?\'\'\'|"(?:[^"\\\n]|\\.)*"|\'(?:[^\'\\\n]|\\.)*\'|<[^<>\s"{}|^`\\]*>|#[^\n]*'
)
_PREFIXED_LOCAL = re.compile(r"^[A-Za-z_][A-Za-z0-9_-]*$")


class Text2SPARQLError(Text2QueryError):
    """The LLM's answer could not be run: invalid or non-read-only SPARQL."""


@dataclass
class Text2SPARQLResult:
    """Answer to a natural-language question.

    Attributes:
        sparql: The SPARQL query generated by the LLM (and executed).
        records: Query results, shaped like ``graph.query(sparql)``.
        metadata: Extra metadata (``sparql``).
    """

    sparql: str
    records: List[Dict[str, Any]]
    metadata: Dict[str, Any] = field(default_factory=dict)


def extract_sparql(text: str) -> str:
    """Return the SPARQL in an LLM answer (inside a code fence if there is one)."""
    match = re.search(r"```(?:[a-zA-Z]+\n)?(.*?)```", text, re.DOTALL)
    return (match.group(1) if match else text).strip()


def is_read_only_sparql(query: str) -> bool:
    """Whether *query* is a SPARQL query form that can't modify data or
    reach another server (no update operation, no ``SERVICE``). String
    literals, IRIs and comments are ignored."""
    from .jena_graph import _body, _first_word, is_sparql

    if not is_sparql(query):
        return False
    body, _ = _body(query)
    if _first_word(body) not in _QUERY_FORMS:
        return False
    return not _FORBIDDEN.search(_STRINGS_AND_IRIS.sub(" ", query))


def _name(namespace: str, kind: str, prefix: str, name: str) -> str:
    if _PREFIXED_LOCAL.match(name):
        return f"{prefix}:{name}"
    return f"<{namespace}{kind}/{quote(name, safe='')}>"


def format_sparql_schema(
    namespace: str,
    node_props: Dict[str, Sequence[Tuple[str, str]]],
    rel_props: Dict[str, Sequence[Tuple[str, str]]],
    relationships: Sequence[Tuple[str, str, str]],
) -> str:
    """Render a graph schema (see :func:`cvcdocdb.text2cypher.collect_schema`)
    in the RDF vocabulary of :class:`~cvcdocdb.jena_graph.JenaGraph`."""

    def props(owner: str, items: Sequence[Tuple[str, str]]) -> str:
        listed = ", ".join(_name(namespace, "prop", "prop", p) + ": " + t for p, t in items)
        return owner + " {" + listed + "}"

    lines = [
        f"PREFIX label: <{namespace}label/>",
        f"PREFIX prop: <{namespace}prop/>",
        f"PREFIX rel: <{namespace}rel/>",
        "Node classes (rdf:type) and their properties:",
        *(props(_name(namespace, "label", "label", label), items) for label, items in node_props.items()),
        "Relationship properties (RDF 1.2 annotations on the relationship triple):",
        *(props(_name(namespace, "rel", "rel", rel), items) for rel, items in rel_props.items()),
        "The relationships:",
        *(
            "?a a " + _name(namespace, "label", "label", s) + " . ?a " + _name(namespace, "rel", "rel", t)
            + " ?b . ?b a " + _name(namespace, "label", "label", e)
            for s, t, e in relationships
        ),
    ]
    return "\n".join(lines)


def _is_sparql_graph(graph: Any) -> bool:
    try:
        from .jena_graph import JenaGraph
    except ImportError:  # pragma: no cover
        return False
    return isinstance(graph, JenaGraph)


class Text2SPARQL:
    """Ask natural-language questions to a SPARQL-backed cvcdocdb graph.

    Args:
        graph: A :class:`~cvcdocdb.jena_graph.JenaGraph`.
        llm: The LLM handle — a ``prompt: str -> str`` callable, or an object
            with ``invoke(prompt)`` returning an answer with ``.content``.
        schema: Schema text for the prompt; introspected when omitted.
        examples: Optional example question/SPARQL pairs for the prompt.
        custom_prompt: Optional prompt template replacing
            :data:`DEFAULT_SPARQL_PROMPT`, with ``{schema}``, ``{examples}``
            and ``{query_text}`` placeholders.

    Raises:
        TypeError: If *graph* isn't a SPARQL backend, or *llm* is neither a
            callable nor an object with ``invoke``.
    """

    def __init__(
        self,
        graph: Any,
        llm: Any,
        *,
        schema: Optional[str] = None,
        examples: Optional[List[str]] = None,
        custom_prompt: Optional[str] = None,
    ) -> None:
        if not _is_sparql_graph(graph):
            raise TypeError(
                f"Text2SPARQL needs a SPARQL backend (JenaGraph), got {type(graph).__name__}; "
                "use Text2Cypher, or Text2Query to pick automatically"
            )
        if not callable(getattr(llm, "invoke", None)):
            if not callable(llm):
                raise TypeError(
                    "llm must be a callable prompt -> str or an object with an "
                    f"'invoke' method, got {type(llm).__name__}"
                )
            llm = CallableLLM(llm)
        self.graph = graph
        self.llm = llm
        self.examples = examples
        self.custom_prompt = custom_prompt
        self.schema = schema if schema is not None else format_sparql_schema(
            graph._mapping.namespace, *collect_schema(graph)
        )

    def _prompt(self, question: str) -> str:
        return (self.custom_prompt or DEFAULT_SPARQL_PROMPT).format(
            schema=self.schema,
            examples="\n".join(self.examples or []),
            query_text=question,
        )

    def query(self, question: str) -> Text2SPARQLResult:
        """Translate *question* to SPARQL with the LLM, run it, return the rows.

        Raises:
            Text2SPARQLError: If the generated SPARQL is invalid or not
                read-only (nothing is executed in that case).
        """
        sparql = extract_sparql(self.llm.invoke(self._prompt(question)).content)
        if not is_read_only_sparql(sparql):
            raise Text2SPARQLError(f"Refusing to execute non-read-only SPARQL: {sparql}")
        try:
            records = self.graph.query(sparql)
        except Exception as exc:
            raise Text2SPARQLError(f"Failed to run generated SPARQL {sparql!r}: {exc}") from exc
        return Text2SPARQLResult(sparql=sparql, records=records, metadata={"sparql": sparql})
